import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"
 
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const currencySymbols: { [key: string]: string } = {
  "United States": "$",
  "United Arab Emirates": "د.إ",
  "Afghanistan": "؋",
  "Albania": "Lek",
  "Armenia": "֏",
  "Netherlands Antilles": "ƒ",
  "Angola": "Kz",
  "Argentina": "$",
  "Australia": "$",
  "Aruba": "ƒ",
  "Azerbaijan": "₼",
  "Bosnia and Herzegovina": "KM",
  "Barbados": "$",
  "Bangladesh": "৳",
  "Bulgaria": "лв",
  "Bahrain": ".د.ب",
  "Burundi": "BIF",
  "Bermuda": "$",
  "Brunei": "$",
  "Bolivia": "Bs.",
  "Brazil": "R$",
  "Bahamas": "$",
  "Bhutan": "Nu.",
  "Botswana": "P",
  "Belarus": "Br",
  "Belize": "$",
  "Canada": "$",
  "Democratic Republic of the Congo": "CFA",
  "Switzerland": "Fr.",
  "Chile": "$",
  "China": "¥",
  "Colombia": "$",
  "Costa Rica": "₡",
  "Cuba": "₱",
  "Cape Verde": "$",
  "Czech Republic": "Kč",
  "Djibouti": "Fdj",
  "Denmark": "kr",
  "Dominican Republic": "RD$",
  "Algeria": "دج",
  "Egypt": "ج.م",
  "Eritrea": "Nfa",
  "Ethiopia": "Br",
  "Eurozone": "€",
  "Fiji": "$",
  "Falkland Islands": "£",
  "Faroe Islands": "kr",
  "United Kingdom": "£",
  "Georgia": "₾",
  "Guernsey": "£",
  "Ghana": "₵",
  "Gibraltar": "£",
  "The Gambia": "D",
  "Guinea": "FG",
  "Guatemala": "Q",
  "Guyana": "$",
  "Hong Kong": "$",
  "Honduras": "L",
  "Croatia": "kn",
  "Haiti": "G",
  "Hungary": "Ft",
  "Indonesia": "Rp",
  "Israel": "₪",
  "Isle of Man": "£",
  "India": "₹",
  "Iraq": "د.ع",
  "Iran": "﷼",
  "Iceland": "kr",
  "Jersey": "£",
  "Jamaica": "$",
  "Jordan": "د.ا",
  "Japan": "¥",
  "Kenya": "KSh",
  "Kyrgyzstan": "сом",
  "Cambodia": "៛",
  "Kiribati": "$",
  "Comoros": "Fr",
  "South Korea": "₩",
  "Kuwait": "د.ك",
  "Cayman Islands": "$",
  "Kazakhstan": "₸",
  "Laos": "₭",
  "Lebanon": "ل.ل",
  "Sri Lanka": "Rs",
  "Liberia": "$",
  "Lesotho": "M",
  "Libya": "د.ل",
  "Morocco": "د.م.",
  "Moldova": "lei",
  "Madagascar": "Ar",
  "North Macedonia": "ден",
  "Myanmar": "K",
  "Mongolia": "₮",
  "Macau": "MOP",
  "Mauritania": "MRU",
  "Mauritius": "Rs",
  "Maldives": "MVR",
  "Malawi": "MK",
  "Mexico": "$",
  "Malaysia": "RM",
  "Mozambique": "MT",
  "Namibia": "$",
  "Nigeria": "₦",
  "Nicaragua": "C$",
  "Norway": "kr",
  "Nepal": "₨",
  "New Zealand": "$",
  "Oman": "ر.ع.",
  "Panama": "B/.",
  "Peru": "S/.",
  "Papua New Guinea": "K",
  "Philippines": "₱",
  "Pakistan": "Rs",
  "Poland": "zł",
  "Paraguay": "₲",
  "Qatar": "ر.ق",
  "Romania": "lei",
  "Serbia": "Дин.",
  "Russia": "₽",
  "Rwanda": "Fr",
  "Saudi Arabia": "ر.س",
  "Solomon Islands": "$",
  "Seychelles": "₨",
  "Sudan": "SDG",
  "Sweden": "kr",
  "Singapore": "$",
  "Saint Helena": "£",
  "Sierra Leone": "Le",
  "Sao Tome and Principe": "Db",
  "Somalia": "Sh",
  "Suriname": "$",
  "South Sudan": "SSP",
  "São Tomé and Príncipe": "Db",
  "Syria": "ل.س",
  "Swaziland": "L",
  "Thailand": "฿",
  "Tajikistan": "SM",
  "Turkmenistan": "m",
  "Tunisia": "د.ت",
  "Tonga": "$",
  "Turkey": "₺",
  "Trinidad and Tobago": "$",
  "Tuvalu": "$",
  "Taiwan": "NT$",
  "Tanzania": "Sh",
  "Ukraine": "₴",
  "Uganda": "UGX",
  "Uruguay": "$",
  "Uzbekistan": "лв",
  "Venezuela": "Bs.S",
  "Vietnam": "₫",
  "Vanuatu": "Vt",
  "Samoa": "$",
  "Central African CFA": "CFA",
  "Eastern Caribbean Dollar": "$",
  "International Monetary Fund": "XDR",
  "West African CFA": "CFA",
  "Pacific Franc": "₣",
  "Yemen": "﷼",
  "South Africa": "R",
  "Zambia": "ZK",
  "Zimbabwe": "$"
};